### ISSUE TITLE
Create endpoint with all main measurements per buoy

### ISSUE THREAD

**Issue by mcmcgrath13** [ridatadiscoverycenter/buoy-api#24]
* Add a `summary` table type (or similar name)

`/telemetry/Buoy-720/summary/lastday`

* We'll need to create a `VIEW` in the database with a matching name and the fields we want

**Comment by marecotec** [comment]
We do have sensor sync issues with the system, and this is only going to get worse as we power optimize for the winter (some sensors are now on 6 hour intervals whereas they were on 1 hour intervals prior. We can't realistically sample nutrients (power hungry) on the same cycle as the CTD data.

**Comment by mcmcgrath13** [comment]
Given that, I think it makes sense to go the nested JSON route, so it's easier to grab all the metrics at once for the time period queried, but otherwise leaves the time/collation to the end user.
